info:
  contact: {}
  license: {}
paths:
  /login:
    get:
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 登录
swagger: "2.0"
